#!/usr/bin/env python
"""
word_mode_real_fraction.py

Measure the real-word fraction of words generated by a word-mode character model.
Generates N words (one per sample.py call with --stop_on_newline), checks each
against the full YAWL word list, and reports:
  - real-word fraction (in YAWL)
  - novel-real fraction (real words NOT in the training split)
  - empty-output count and over-length count (treated as non-real)
  - best and final val loss (bpc) from the checkpoint

Usage:
  python py/word_mode_real_fraction.py \
      --models pt/yawl_word_1L1H_e32_untied_cuda_final.pt \
                pt/yawl_word_1L1H_e28_untied_cuda_final.pt \
      --wordlist txt_local/yawl_word_list_width_26.txt \
      --n_words 1000 --max_letters 14 --temperature 0.8 --top_k 40 --seed 42

Multiple --models are evaluated in order; output is one row per model.
The script reproduces the train/val split using train.py's own shuffle+seed
so that the "novel-real" (val) fraction is computable without the checkpoint
needing to store the split.
"""

import argparse
import os
import pickle
import sys
import math
import torch

# Make py/ importable regardless of cwd
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from model import GPTConfig, GPT
from tokenizer import load_tokenizer


def load_model(model_path, device):
    checkpoint = torch.load(model_path, map_location=device, weights_only=False)
    model_args = checkpoint['model_args']
    gptconf = GPTConfig(**model_args)
    import io as _io, contextlib as _cl
    with _cl.redirect_stdout(_io.StringIO()):
        model = GPT(gptconf)
    model.load_state_dict(checkpoint['model'])
    model.to(device)
    model.eval()
    return model, checkpoint


def get_meta_path(model_path):
    base = model_path.replace('.pt', '')
    if '_iter' in base:
        base = base.rsplit('_iter', 1)[0]
    elif base.endswith('_final'):
        base = base[:-6]
    elif base.endswith('_rolling'):
        base = base[:-8]
    return base + '_meta.pkl'


def reproduce_val_words(wordlist_path, val_split=0.1, seed=1337):
    """Attempt to reproduce the train/val split — NOTE: NOT POSSIBLE.

    train.py calls random.shuffle(data_blocks) but only seeds torch (not Python's
    random module), so the shuffle is entropy-based and non-deterministic across
    runs. This function returns None to signal that the split is unavailable.
    """
    return None


@torch.no_grad()
def generate_words(model, tokenizer, device, n_words, max_letters, temperature, top_k, seed):
    """Generate n_words words from a word-mode model, one per sample."""
    newline_ids = tokenizer.encode('\n')
    if not newline_ids:
        raise ValueError("tokenizer has no newline token")
    stop_token_id = newline_ids[0]

    prompt_ids = tokenizer.encode('\n')
    prompt_tensor = torch.tensor(prompt_ids, dtype=torch.long, device=device).unsqueeze(0)

    words = []
    torch.manual_seed(seed)
    for i in range(n_words):
        # Vary seed per sample for diversity (same approach as real_word_fraction.py)
        torch.manual_seed(seed + i)
        y = model.generate(
            prompt_tensor,
            max_new_tokens=max_letters + 2,
            temperature=temperature,
            top_k=top_k if top_k > 0 else None,
            stop_token_id=stop_token_id,
        )
        tokens = y[0].tolist()
        # Decode, strip leading \n prompt, strip trailing \n
        text = tokenizer.decode(tokens)
        # Remove leading newline (the prompt)
        if text.startswith('\n'):
            text = text[1:]
        # Strip trailing newline if present (stop token)
        if text.endswith('\n'):
            text = text[:-1]
        words.append(text)
    return words


def evaluate(model_path, wordlist_path, n_words, max_letters, temperature, top_k, seed, device):
    model, checkpoint = load_model(model_path, device)
    meta_path = get_meta_path(model_path)
    tokenizer = load_tokenizer(meta_path)

    # YAWL set
    with open(wordlist_path, 'r', encoding='utf-8') as f:
        yawl_set = set(line.strip() for line in f if line.strip())

    # Val split: not reproducible (train.py doesn't seed Python's random module)
    # novel_real_frac is reported as N/A.

    # Generate words
    words = generate_words(model, tokenizer, device, n_words, max_letters, temperature, top_k, seed)

    # Classify
    n_empty = sum(1 for w in words if w == '')
    n_overlong = sum(1 for w in words if len(w) > max_letters and w != '')
    n_real = sum(1 for w in words if w in yawl_set)
    n_novel_real = None   # val split non-reproducible
    real_frac = n_real / n_words if n_words else 0.0
    novel_real_frac = None

    # Val loss from checkpoint
    best_val = checkpoint.get('best_val_loss')
    best_val_bpc = best_val / math.log(2) if best_val else None
    # iter_num
    iter_num = checkpoint.get('iter_num', '?')
    # n_embd from model_args
    n_embd = checkpoint['model_args'].get('n_embd', '?')

    # Parameter count
    n_params = sum(p.numel() for p in model.parameters())

    return {
        'model_path': model_path,
        'n_embd': n_embd,
        'iter_num': iter_num,
        'n_params': n_params,
        'n_words': n_words,
        'n_real': n_real,
        'n_novel_real': n_novel_real,  # None — val split not reproducible
        'n_empty': n_empty,
        'n_overlong': n_overlong,
        'real_frac': real_frac,
        'novel_real_frac': novel_real_frac,
        'best_val_bpc': best_val_bpc,
        'sample_words': words[:20],
    }


def main():
    parser = argparse.ArgumentParser(description='Real-word fraction for word-mode char models')
    parser.add_argument('--models', nargs='+', required=True, help='Checkpoint paths (.pt files)')
    parser.add_argument('--wordlist', required=True, help='YAWL word list (one word per line)')
    parser.add_argument('--n_words', type=int, default=1000, help='Words to generate per checkpoint')
    parser.add_argument('--max_letters', type=int, default=14, help='Max word length; longer = non-real')
    parser.add_argument('--temperature', type=float, default=0.8)
    parser.add_argument('--top_k', type=int, default=40)
    parser.add_argument('--seed', type=int, default=42)
    parser.add_argument('--tsv', type=str, default=None, help='Path to write TSV results')
    args = parser.parse_args()

    device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
    print(f"device: {device}")
    print(f"wordlist: {args.wordlist}  ({sum(1 for _ in open(args.wordlist))} words)")
    print()

    header = f"{'model':<55} {'e':>4} {'iter':>6} {'params':>8} {'real%':>7} {'novel%':>7} {'empty':>5} {'long':>5} {'valBPC':>7}"
    print("Note: novel% (val-split) is N/A — train.py does not seed Python's random.shuffle")
    print(header)
    print('-' * len(header))

    rows = []
    for mp in args.models:
        if not os.path.exists(mp):
            print(f"  MISSING: {mp}")
            continue
        r = evaluate(mp, args.wordlist, args.n_words, args.max_letters,
                     args.temperature, args.top_k, args.seed, device)
        bpc_str = f"{r['best_val_bpc']:.4f}" if r['best_val_bpc'] else "  ?"
        print(f"{os.path.basename(r['model_path']):<55} {r['n_embd']:>4} {r['iter_num']:>6} "
              f"{r['n_params']:>8,} {100*r['real_frac']:>6.1f}% {'N/A':>7} "
              f"{r['n_empty']:>5} {r['n_overlong']:>5} {bpc_str:>7}")
        print(f"  samples: {' | '.join(r['sample_words'][:10])}")
        print(f"           {' | '.join(r['sample_words'][10:20])}")
        print()
        rows.append(r)

    if args.tsv and rows:
        with open(args.tsv, 'w') as f:
            f.write('model\tn_embd\titer\tn_params\treal_frac\tnovel_real_frac\tn_empty\tn_overlong\tbest_val_bpc\n')
            for r in rows:
                bpc = f"{r['best_val_bpc']:.6f}" if r['best_val_bpc'] else ''
                f.write(f"{os.path.basename(r['model_path'])}\t{r['n_embd']}\t{r['iter_num']}\t"
                        f"{r['n_params']}\t{r['real_frac']:.6f}\t\t"
                        f"{r['n_empty']}\t{r['n_overlong']}\t{bpc}\n")
        print(f"TSV written: {args.tsv}")


if __name__ == '__main__':
    main()
